### ISSUE TITLE
A mistake in axis()

### ISSUE THREAD

**Issue by vvvxo** [affenwiesel/matlab-formatter-vscode#22] opened 2019-01-08 15:22 UTC
As axis([-3 3 -3 3]) while be format to axis(-3 3 - 3 3])

**Comment by affenwiesel** [comment] 2019-01-08 23:00
Assuming that the missing [ is just a typo, this has already been discussed.
Duplicate of #21

**Closed by affenwiesel** 2019-01-08 23:00 UTC
