### ISSUE TITLE
unrecognizable characters with Chinese comments

### ISSUE THREAD

**Issue by hao3han3** [affenwiesel/matlab-formatter-vscode#25] opened 2019-03-05 10:53 UTC
First Thank you of your working

Than I think there is a bug for Chinese comments, which I thought link to the file code of UTF8 and GB2312.

as a default, the m-files which have Chinese comments will be coded in GB2312 (or somthing not UTF8, I do not know about other language)

with current version of extention, all Chinese will be unrecognizable after the formating.

In one chance I tried fromating with a m-file coding with UTF8 and it also has Chinese comments, and there is no problme after formatting.

there is a simily issue here [Chinese comments gibberish](https://github.com/affenwiesel/matlab-formatter-vscode/issues/4) #4 

there are two pictures to show you how the issue is:
befere the formating:
![before](https://user-images.githubusercontent.com/46490355/53800507-2eaaa100-3f3d-11e9-8df5-26bbd47b9b59.png)
after the  formating:
![after](https://user-images.githubusercontent.com/46490355/53800518-366a4580-3f3d-11e9-8b07-f5d6cbff1327.png)

Additionlly, if I transfer the GB2312 file to UTF8 file, the formating is fail. I do not know the reason....

**Comment by affenwiesel** [comment] 2019-03-13 12:13
As mentioned before, since I don't speek chinese it is hard for me to reproduce this error.
I would appreciate if someone who is actually using chinese comments came up with a fix for this.
One solution that has been suggested was to use `sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf8')`. However, while this (at least partially) solved the issues with chinese letters, it messed up other unicode characters (e.g. greek characters which I personally use).

**Comment by leewi9** [comment] 2019-03-17 08:47
change line 218 to:
`with open(filename, 'r', encoding='UTF-8') as f:`

**Comment by affenwiesel** [comment] 2019-03-17 09:16
This also causes errors with e.g. greek letters

**Comment by hao3han3** [comment] 2019-03-20 10:31
why do not use "chardet.detect" ? 
detect the code, editing with this code, and then saved with code?

**Comment by affenwiesel** [comment] 2019-03-20 11:27
How exactly would this be implemented?

**Comment by leewi9** [comment] 2019-03-20 12:54
i've done some search about it, turn out auto detect string encoding isn't easy as it looks like, please inform me if anyone find a good solution.

**Comment by hao3han3** [comment] 2019-03-20 14:36
> How exactly would this be implemented?

sorry, I am not good at python and vs code add-in programing, thus I can not privide it.
but I think you can find some examples in this link: [https://chardet.readthedocs.io/en/latest/usage.html](https://chardet.readthedocs.io/en/latest/usage.html).

I think there may be two possible solutions:
1, ask vscode " what code is this file" and then let vscode do the job of  "save the file as <the code you want>" .
or
2, in python to check the file code, and then tell vscode to save this file in this code.

**Closed** 2019-03-25 18:16 UTC
